[build-system]
requires = [
  "setuptools>=77.3.1",
  "setuptools_scm>=8.0.0",
]
build-backend = 'setuptools.build_meta'

[project]
name = "sphinx-astropy"
license = "BSD-3-Clause"
license-files = ["LICENSE.rst"]
authors = [{name = "The Astropy Developers", email = "astropy.team@gmail.com"}]
classifiers = [
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
description = "Sphinx extensions and configuration specific to the Astropy project"
readme = {file = "README.rst", content-type = "text/x-rst"}
requires-python = ">=3.10"
dynamic = ["version"]
dependencies = [
  "astropy-sphinx-theme>=3.0",
  "numpydoc>=1.0.0",
  "packaging>=17.0",
  "pillow>=8.3.2",
  "pytest-doctestplus>=1.3.0",
  "sphinx-automodapi>=0.3",
  "sphinx-gallery>=0.11.0",
  "sphinx>=4.0.0",
  "sphinxcontrib-jquery>=4.0.0",
]

[project.optional-dependencies]
confv2 = [
  "pydata-sphinx-theme",
  "sphinx-copybutton",
]
confv3 = [
  "sphinx-astropy[confv2]",
  "astropy-sphinx-theme>=3.0.0",
]
all = ["astropy"]
tests = ["pytest"]

[tool.setuptools.package-data]
"sphinx_astropy" = ["local/*"]

[tool.setuptools_scm]
version_file = "sphinx_astropy/version.py"